In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix

In [3]:
# using original train dataset
train_df = pd.read_csv("wordEmbeddingTrain.csv")
test_df = pd.read_csv("wordEmbeddingTest.csv")

In [4]:
del train_df['index']
print('Shape of the train dataset: ' + str(train_df.shape))
train_df.head()

Shape of the train dataset: (29635, 101)


0         1         2  ...        98        99   labels
0 -0.140486 -0.708271 -0.382102  ...  0.497229  0.458049       cs
1  0.411015 -0.790592 -0.897963  ...  0.500449  0.182480  math.DS
2 -0.274633 -1.035805 -0.625783  ...  0.263815  0.319821       cs
3 -0.005348 -0.107721  0.211413  ...  0.238857  0.295559       cs
4  0.331930 -0.507421 -0.363805  ...  0.398557  0.600941       cs

[5 rows x 101 columns]

In [5]:
#Creating the dependent variable class
factor = pd.factorize(train_df['labels'])
train_df.labels = factor[0]
definitions = factor[1]

print(len(definitions), '\n')
print(train_df.labels)

100 

0         0
1         1
2         0
3         0
4         0
         ..
29630     0
29631    14
29632     0
29633     0
29634    14
Name: labels, Length: 29635, dtype: int64


In [6]:
#Splitting the data into independent and dependent variables

X = train_df.iloc[:,0:100].values
y = train_df.iloc[:,100].values

In [7]:
# Creating the Training and Test set from data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 21)

In [8]:
# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
# multinomial
# Determine optimised C 
# https://stackoverflow.com/questions/60868629/valueerror-solver-lbfgs-supports-only-l2-or-none-penalties-got-l1-penalty
# https://stackoverflow.com/questions/32074630/training-logistic-regression-using-scikit-learn-for-multi-class-classification
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
# https://stackoverflow.com/questions/38640109/logistic-regression-python-solvers-defintions

parameters = {'C':[0.03, 0.04, 0.05, 0.06, 0.07, 0.1, 0.5]}
grid_lr = GridSearchCV(LogisticRegression(multi_class='multinomial', penalty= 'l2', solver = 'saga', max_iter=500), parameters, cv=3, refit = True, verbose = 10)
grid_lr.fit(X_train, y_train)

print(grid_lr.best_params_)
print(grid_lr.best_estimator_)

Fitting 3 folds for each of 7 candidates, totalling 21 fits
[CV] C=0.03 ..........................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .............................. C=0.03, score=0.532, total= 2.0min
[CV] C=0.03 ..........................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.0min remaining:    0.0s


[CV] .............................. C=0.03, score=0.529, total= 2.0min
[CV] C=0.03 ..........................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  4.0min remaining:    0.0s


[CV] .............................. C=0.03, score=0.531, total= 2.0min
[CV] C=0.04 ..........................................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  6.0min remaining:    0.0s


[CV] .............................. C=0.04, score=0.532, total= 2.3min
[CV] C=0.04 ..........................................................


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:  8.3min remaining:    0.0s


[CV] .............................. C=0.04, score=0.532, total= 2.2min
[CV] C=0.04 ..........................................................


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 10.4min remaining:    0.0s


[CV] .............................. C=0.04, score=0.531, total= 2.2min
[CV] C=0.05 ..........................................................


[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed: 12.6min remaining:    0.0s


[CV] .............................. C=0.05, score=0.531, total= 2.5min
[CV] C=0.05 ..........................................................


[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed: 15.1min remaining:    0.0s


[CV] .............................. C=0.05, score=0.530, total= 2.4min
[CV] C=0.05 ..........................................................


[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed: 17.5min remaining:    0.0s


[CV] .............................. C=0.05, score=0.530, total= 2.3min
[CV] C=0.06 ..........................................................


[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed: 19.8min remaining:    0.0s


[CV] .............................. C=0.06, score=0.531, total= 2.7min
[CV] C=0.06 ..........................................................
[CV] .............................. C=0.06, score=0.531, total= 2.6min
[CV] C=0.06 ..........................................................
[CV] .............................. C=0.06, score=0.530, total= 2.5min
[CV] C=0.07 ..........................................................
[CV] .............................. C=0.07, score=0.530, total= 2.8min
[CV] C=0.07 ..........................................................
[CV] .............................. C=0.07, score=0.531, total= 2.7min
[CV] C=0.07 ..........................................................
[CV] .............................. C=0.07, score=0.530, total= 2.6min
[CV] C=0.1 ...........................................................
[CV] ............................... C=0.1, score=0.526, total= 3.3min
[CV] C=0.1 ...........................................................
[CV] .

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


[CV] ............................... C=0.5, score=0.516, total= 4.9min
[CV] C=0.5 ...........................................................


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


[CV] ............................... C=0.5, score=0.517, total= 4.9min
[CV] C=0.5 ...........................................................


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
[Parallel(n_jobs=1)]: Done  21 out of  21 | elapsed: 59.8min finished


[CV] ............................... C=0.5, score=0.516, total= 4.9min
{'C': 0.04}
LogisticRegression(C=0.04, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=500,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)


In [12]:
# Predicting the Test set results
y_predictition = grid_lr.predict(X_test)

In [13]:
# Performance metrics
recall = recall_score(y_test, y_predictition, average='macro')
precision = precision_score(y_test, y_predictition, average='macro')
f1score = f1_score(y_test, y_predictition, average='macro')
accuracy = accuracy_score(y_test, y_predictition)

print('Confusion Matrix:\n',confusion_matrix(y_test, y_predictition),'\n')
print('Accuracy:', str(accuracy))
print('Precision:', str(precision))
print('Recall:', str(recall))
print('F1 score:', str(f1score))

Confusion Matrix:
 [[1764    2   11 ...    0    0    0]
 [  17   36    0 ...    0    0    0]
 [ 132    0    2 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   3    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]] 

Accuracy: 0.5348405601484731
Precision: 0.26712530255594935
Recall: 0.20716071943705647
F1 score: 0.21534968733774457


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
# test
test_data = test_df.iloc[:,0:100].values
test_data_scaled = scaler.fit_transform(test_data)
test_predictition = grid_lr.predict(test_data_scaled)

In [15]:
test_df=test_df.rename(columns = {'index':'test_id'})
test_df['label'] = definitions[test_predictition] # convert to original labels
test_df.drop(train_df.iloc[:,0:100], inplace=True, axis=1)

In [16]:
test_df.head()

test_id           label
0        1         stat.AP
1        2              cs
2        3              cs
3        4         math.RT
4        5  physics.optics

In [17]:
test_df.to_csv('./Predictions_lr_multinomial_saga_word2vec.csv', index = False)